name: "Build kernels"

env:
  OUT_DIR: "${{ github.workspace }}/out"

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    name: "Build kernel"
    runs-on: ubuntu-22.04
    env:
      WORKSPACE: ${{ github.workspace }}
      KERNEL_NAME: BKLYN-Kernel
      KERNEL_REPO: "https://github.com/MK-986123/BKLYN-Kernel.git"
      KERNEL_BRANCH: "android14-6.1-lts"
      KERNEL_DEVICE: "samsung_dm3q"
      DEFCONFIG_NAME: "gki_defconfig"
      ARCH: arm64
      withMagisk: true
      useAnykernel: true
      release: true
    steps:
      - name: "Get build date"
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV
        shell: bash

      - name: "Install prerequisites"
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc flex bison libssl-dev curl git zip ftp gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi lftp zstd wget libfl-dev python2 python3 libarchive-tools libelf-dev libz-dev binutils-dev
        shell: bash

      - name: "Setup Anykernel3"
        run: |
          git clone --recursive --depth=1 -j $(nproc) --branch master https://github.com/osm0sis/AnyKernel3 AnyKernel3
          echo "Setup Anykernel3 => (https://github.com/osm0sis/AnyKernel3)"
        shell: bash

      - name: "Clone kernel source"
        run: |
          git clone --recursive --depth=1 -j $(nproc) --branch $KERNEL_BRANCH $KERNEL_REPO $KERNEL_NAME
          echo "Clone kernel source => ($KERNEL_REPO)"
        shell: bash

      - name: "Get toolchains"
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git toolchains/proton-clang
          echo "Toolchains setup complete."
        shell: bash

      - name: "Set args"
        id: generate-args
        env:
          THREAD: $(nproc --all)
        run: |
          ARCH=arm64
          CC=toolchains/proton-clang/bin/clang
          args="-j${{ env.THREAD }} O=${{ env.OUT_DIR }} ARCH=$ARCH CC=${{ env.WORKSPACE }}/$CC"
          echo "args=$args" >> $GITHUB_OUTPUT
        shell: bash

      - name: "Update Magisk"
        working-directory: ${{ env.KERNEL_NAME }}
        env:
          arch: arm64
        if: ${{ env.withMagisk == 'true' }}
        run: |
          git clone --depth=1 https://github.com/topjohnwu/Magisk.git
          cd Magisk
          ./build.py ndk
          cp -f magiskboot ${{ env.WORKSPACE }}/$KERNEL_NAME/anykernel/tools/
          echo "Magisk setup complete."
        shell: bash

      - name: "Make defconfig"
        working-directory: ${{ env.KERNEL_NAME }}
        env:
          args: ${{ steps.generate-args.outputs.args }}
          arch: arm64
        run: |
          make ${{ env.args }} ${{ env.DEFCONFIG_NAME }}
        shell: bash

      - name: "Build kernel"
        working-directory: ${{ env.KERNEL_NAME }}
        env:
          args: ${{ steps.generate-args.outputs.args }}
        run: |
          make $args
        shell: bash

      - name: "Upload Image"
        uses: actions/upload-artifact@v3
        with:
          name: Image-${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}-${{ steps.date.outputs.date }}
          path: ${{ env.OUT_DIR }}/arch/arm64/boot/Image
          retention-days: 7
        continue-on-error: true

      - name: "Upload Image.gz"
        uses: actions/upload-artifact@v3
        with:
          name: Image.gz-${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}-${{ steps.date.outputs.date }}
          path: ${{ env.OUT_DIR }}/arch/arm64/boot/Image.gz
          retention-days: 7
        continue-on-error: true

      - name: "Upload dtb"
        uses: actions/upload-artifact@v3
        with:
          name: dtb-${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}-${{ steps.date.outputs.date }}
          path: ${{ env.OUT_DIR }}/arch/arm64/boot/dtb
          retention-days: 7
        continue-on-error: true

      - name: "Upload dtbo.img"
        uses: actions/upload-artifact@v3
        with:
          name: dtbo.img-${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}-${{ steps.date.outputs.date }}
          path: ${{ env.OUT_DIR }}/arch/arm64/boot/dtbo.img
          retention-days: 7
        continue-on-error: true

      - name: "Pack AnyKernel3.zip"
        if: ${{ env.useAnykernel == 'true' }}
        env:
          arch: arm64
          anykernel: "${{ env.WORKSPACE }}/${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}_${{ steps.date.outputs.date }}"
        run: |
          ls -al
          if [ -e "${{ env.OUT_DIR }}/arch/${{ env.arch }}/boot/Image.gz-dtb" ]; then
            cp -f ${{ env.OUT_DIR }}/arch/${{ env.arch }}/boot/Image.gz-dtb ./AnyKernel3/
          fi
          cd AnyKernel3/
          zip -q -r "${{ env.anykernel }}.zip" *
        shell: bash

      - name: "Upload AnyKernel3 image"
        uses: actions/upload-artifact@v3
        if: ${{ env.useAnykernel == 'true' }}
        with:
          name: "${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}_${{ steps.date.outputs.date }}"
          path: AnyKernel3/*

      - name: "Create GitHub Release"
        continue-on-error: true
        uses: softprops/action-gh-release@v1
        if: ${{ env.useAnykernel == 'true' && env.release == 'true' }}
        with:
          tag_name: v${{ steps.date.outputs.date }}.${{ github.run_number }}
          files: "${{ env.WORKSPACE }}/${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}_${{ steps.date.outputs.date }}.zip"
          generate_release_notes: true
